server:
  port: 8189
  servlet:
    context-path: /market-core

integrations:
  cart-service:
    url: http://localhost:8190/market-cart
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000